# Generated by Django 3.1.3 on 2021-10-23 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
